# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3e56daacedaf89657073f2dab9d3fce6bb53519155bfe51e09cfe1b6c4ee94a6325ef4db104eea1f9422331b85d16aa0e8d86c63f28a3dd9871c4859cbf1d1b

test:
  secret_key_base: 898837ac81f04f46f67faca1445905da836b6713fa2a4133fd02043f4b407e9e54281fc6bb973af1bb822f8e9e1777760594e114adfcf33d02593d0035863792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
